name: Build Releases
on:
  push:
    tags:
      - v*midori*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release-cross:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            toolchain: stable
          - target: aarch64-unknown-linux-gnu
            toolchain: stable
          - target: x86_64-unknown-linux-musl
            toolchain: stable
          - target: aarch64-unknown-linux-musl
            toolchain: stable

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name: Install LLVM and Clang
        run: sudo apt install -y clang

      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install ${{ matrix.platform.toolchain }}
          rustup default ${{ matrix.platform.toolchain }}
          rustup override set ${{ matrix.platform.toolchain }}

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build ${{ matrix.platform.target }}
        timeout-minutes: 120
        run: |
          compile_target=${{ matrix.platform.target }}
          compile_features="-f full-extra"
          cd build
          ./build-release -t ${{ matrix.platform.target }} $compile_features $compile_compress $compile_nightly $compile_cargo_flags

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/release/*.tar.xz
          tag_name: ${{ inputs.tag || github.ref_name }}